name: ci
on:
  workflow_dispatch: # Robotu tamamen manuel (elle basmalı) yapar.

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract archive directly to main
        run: |
          unzip -o resimler.zip
          rm resimler.zip

      - name: Commit and push changes as developer
        run: |
          git config --global user.name "Demirtris"
          git config --global user.email "demirtris@://github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "update"
          git push
